feature: export model endpoint
brmodeloweb/brmodelo-app pull request #213
Opened 2021-10-28 13:27 UTC by feekosta

This PR adds the necessary structure to export model

Resolves #75

2021-10-30 15:45 UTC, miltonbsn commented on server_app/model/handler.js
> +			"Content-Disposition": `attachment; filename=${modelId}.brm`,
Acredito que o nome do arquivo poderia ser o nome do modelo e não o id, o que acha sobre isso?

2021-10-30 15:50 UTC, miltonbsn commented on server_app/app.js
> +});
Eu achei criativa a solução, mas estava pensando em montar um arquivo no server e mandar o usar o wrapper [download](http://expressjs.com/en/api.html#res.download) do express. Podemos discutir sobre isso? Estou aberto a diferentes alternativas mas acho interessante um debate aqui.

2021-10-30 15:59 UTC, miltonbsn requested changes
- Código muito claro e bem escrito ✅ 
- Testes coerentes com excelente cobertura ✅ 
- A solução cumpre os requisitos ✅  

Vou deixar como request change apenas para ouvir tuas considerações nos pontos anotados ⚠️

2021-11-09 02:12 UTC, miltonbsn commented
@feekosta podemos marcar uma meeting para discutir esses assuntos?

2021-11-09 22:21 UTC, feekosta commented
> @feekosta podemos marcar uma meeting para discutir esses assuntos?

@miltonbsn podemos marcar sim.

2021-11-09 22:24 UTC, feekosta commented on server_app/app.js
> +});
Então, não entendi muito bem a proposta utilizando o download do express. Esse middleware é utilizado no upload do documento para importação. Nesse caso ele irá pegar o conteúdo do arquivo e colocar no body da requisição.

2021-11-10 04:50 UTC, miltonbsn approved these changes
Amazing contribution @feekosta (bigpphill)!! 

You are the best! 👑 ⭐

2021-11-10 07:15 UTC, merged