Update README.md
brmodeloweb/brmodelo-app pull request #275
Opened 2021-12-01 23:15 UTC by idmarjr

## Summary

- Add extra links  to requirements section
- Remove outdated information about one time only database steps
- Add links about how to start MongoDB in _Running application_ block
- Add disclaimer about Docker setup]
- Change _Tests_ section to a ordered list of instructions

2021-12-01 23:56 UTC, ArthurMota9 requested changes

2021-12-01 23:56 UTC, ArthurMota9 commented on README.md
> +- [Node.js](https://nodejs.org/) (Strongly recomended to install it via [nvm](https://github.com/nvm-sh/nvm#readme) or [n](https://github.com/tj/n#readme))
```suggestion
- [Node.js](https://nodejs.org/) (Strongly recommended to install it via [nvm](https://github.com/nvm-sh/nvm#readme) or [n](https://github.com/tj/n#readme))
```

2021-12-02 00:12 UTC, ArthurMota9 approved these changes

2021-12-02 02:22 UTC, miltonbsn approved these changes

2021-12-02 11:01 UTC, merged