Refac user login
brmodeloweb/brmodelo-app pull request #99
Opened 2020-06-06 21:32 UTC by miltonbsn

2020-06-09 02:45 UTC, miltonbsn commented
@feekosta can I have your first thoughts here?

2020-06-09 22:29 UTC, feekosta requested changes

2020-06-09 22:29 UTC, feekosta commented on server_app/user/service.js
> +        resolve({
return in the if, to not execute the rest of the code

2020-06-09 22:29 UTC, feekosta commented on server_app/user/service.js
> +        reject({"code": "USER_ERROR_ALREADY_EXISTS"});
return in the if, to not execute the rest of the code

2020-06-14 21:37 UTC, miltonbsn commented
@rpuggian you may be interested on this

2020-06-15 21:14 UTC, feekosta approved these changes

2020-06-15 21:23 UTC, rpuggian commented on server_app/user/service.js
> +          "sessionId": sessionId,
Miltão, What do you think about leaving the about leaving the responsibility of setting up the user session to the handler?

2020-06-15 21:30 UTC, rpuggian commented on server_app/user/handler.js
> +    const userSession = await userService.login({username, password, sessionId});
Maybe you can build the user session here, and just find the user in the userService using the password encryption.

2020-06-18 19:44 UTC, idmarjr commented
Folks, are we good to go here?

2020-06-19 00:16 UTC, merged